### PR TITLE
Fixes cancel btn & detect iPadOS desktop-class browsing mode

### PR DESCRIPTION
**Pull request by chown9835**
In some cases, the cancel button may apply css from browser default user-agent stylesheet. So it will looks like a "native button".

I added two lines to "reset" the button from browser default user-agent stylesheet.

Before:
Screen Shot 2019-10-22 at 11 21 15 AM

After:
Screen Shot 2019-10-22 at 11 28 59 AM

### CODE REVIEW

**Comment by chown9835** [comment]
Detect and support for iPadOS desktop-class browsing mode. Refer to issue #15 .

--
The Safari on new iPadOS 13 will act like a "desktop browser" by default, and Apple calls it "desktop-class browsing".

Maybe we should considering to add an option like "promptOniPad" for some situations we don't wanna that message prompt on iPad.

**Comment by chrisdancee** [comment]
Thanks a lot for the PR, very much appreciated! I can address the issues tomorrow unless you get to them first. Then will version and release tomorrow evening (GMT)

**Comment by chrisdancee** [comment]
The prompt on iPad prop seems like a good idea too. I will look into adding in a separate PR.

Just to confirm, the screenshots you’ve posted are showing the iOS version < 13 icons. This also means that the dark mode will not be working. Are the correct classes (.legacy for < 13, .modern for 13) being added for iPadOS after this change?

**Comment by chown9835** [comment]
The screenshots are taken from iOS 12 simulator. Dark mode works, and iOS 13 icon also works well!

Overlay issue has been addressed, checkout this commit: https://github.com/chrisdancee/react-ios-pwa-prompt/commit/8e6b42e80173b1d42fe1bf53ebf849979a37ae12

Thank you so much for all works on this project, it’s very helpful. Have a great day!

**Comment by enocmontiel** [comment]
> Thanks a lot for the PR, very much appreciated! I can address the issues tomorrow unless you get to them first. Then will version and release tomorrow evening (GMT)

Waiting for that! 😄

**Comment by chrisdancee** [comment]
Going to merge now and address the visual bugs before releasing. Thanks a lot for the input @chown9835

**Comment by chrisdancee** [comment]
Just merged the changes here :) 

https://github.com/chrisdancee/react-ios-pwa-prompt/pull/24

**Pull request merged**
